/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

void delay(void){
	for(uint32_t i = 0; i < 300000; i++);
}

int main(void)
{

	/*
	 * Setting the address of registers
	 */
	RCC_AHB1ENR_t *pClkCtrlReg = (RCC_AHB1ENR_t *) 0x40023830;
	GPIOx_MODER_t *pPortDModeReg = (GPIOx_MODER_t *) 0x40020C00;
	GPIOx_PUPDR_t *pPortDPUPDReg = (GPIOx_PUPDR_t *) 0x40020C0C;
	GPIOx_IDR_t *pPortDInReg = (GPIOx_IDR_t *) 0x40020C10;
	GPIOx_ODR_t *pPortDOutReg = (GPIOx_ODR_t *) 0x40020C14;

	// 1. Enable GPIOD clock register
	pClkCtrlReg->gpiod_en = 1;

	// 2. Configure PD0, PD1, PD2, PD3 as output (rows)
	pPortDModeReg->pin_0 = 0;
	pPortDModeReg->pin_1 = 0;
	pPortDModeReg->pin_2 = 0;
	pPortDModeReg->pin_3 = 0;

	pPortDModeReg->pin_0 = 0x01;
	pPortDModeReg->pin_1 = 0x01;
	pPortDModeReg->pin_2 = 0x01;
	pPortDModeReg->pin_3 = 0x01;

	// 3. Configure PD8, PD9, PD10, PD11 as input (cols)
	pPortDModeReg->pin_8 = 0;
	pPortDModeReg->pin_9 = 0;
	pPortDModeReg->pin_10 = 0;
	pPortDModeReg->pin_11 = 0;

	// 4. Enable internal pull-up registers for PD8, PD9, PD10, PD11
	pPortDPUPDReg->pin_8 = 0;
	pPortDPUPDReg->pin_9 = 0;
	pPortDPUPDReg->pin_10 = 0;
	pPortDPUPDReg->pin_11 = 0;

	pPortDPUPDReg->pin_8 = 0x01;
	pPortDPUPDReg->pin_9 = 0x01;
	pPortDPUPDReg->pin_10 = 0x01;
	pPortDPUPDReg->pin_11 = 0x01;

	while(1){
		// 5. Make all rows high
		pPortDOutReg->pin_0 = 1;
		pPortDOutReg->pin_1 = 1;
		pPortDOutReg->pin_2 = 1;
		pPortDOutReg->pin_3 = 1;

		// 6. Make R1 low
		pPortDOutReg->pin_0 = 0;

		// Scan the columns
		// Check C1 (PD8) low or high
		if(!(pPortDInReg->pin_8 == 1)){
			delay();
			printf("1\n");
		}

		// Check C2 (PD9) low or high
		if(!(pPortDInReg->pin_9 == 1)){
			delay();
			printf("2\n");
		}

		// Check C3 (PD10) low or high
		if(!(pPortDInReg->pin_10 == 1)){
			delay();
			printf("3\n");
		}

		// Check C4 (PD11) low or high
		if(!(pPortDInReg->pin_11 == 1)){
			delay();
			printf("A\n");
		}

		// 5. Make all rows high
		pPortDOutReg->pin_0 = 1;
		pPortDOutReg->pin_1 = 1;
		pPortDOutReg->pin_2 = 1;
		pPortDOutReg->pin_3 = 1;

		// 7. Make R2 low
		pPortDOutReg->pin_1 = 0;

		// Scan the columns
		// Check C1 (PD8) low or high
		if(!(pPortDInReg->pin_8 == 1)){
			delay();
			printf("4\n");
		}

		// Check C2 (PD9) low or high
		if(!(pPortDInReg->pin_9 == 1)){
			delay();
			printf("5\n");
		}

		// Check C3 (PD10) low or high
		if(!(pPortDInReg->pin_10 == 1)){
			delay();
			printf("6\n");
		}

		// Check C4 (PD11) low or high
		if(!(pPortDInReg->pin_11 == 1)){
			delay();
			printf("B\n");
		}

		// 5. Make all rows high
		pPortDOutReg->pin_0 = 1;
		pPortDOutReg->pin_1 = 1;
		pPortDOutReg->pin_2 = 1;
		pPortDOutReg->pin_3 = 1;

		// 8. Make R3 low
		pPortDOutReg->pin_2 = 0;

		// Scan the columns
		// Check C1 (PD8) low or high
		if(!(pPortDInReg->pin_8 == 1)){
			delay();
			printf("7\n");
		}

		// Check C2 (PD9) low or high
		if(!(pPortDInReg->pin_9 == 1)){
			delay();
			printf("8\n");
		}

		// Check C3 (PD10) low or high
		if(!(pPortDInReg->pin_10 == 1)){
			delay();
			printf("9\n");
		}

		// Check C4 (PD11) low or high
		if(!(pPortDInReg->pin_11 == 1)){
			delay();
			printf("C\n");
		}

		// 5. Make all rows high
		pPortDOutReg->pin_0 = 1;
		pPortDOutReg->pin_1 = 1;
		pPortDOutReg->pin_2 = 1;
		pPortDOutReg->pin_3 = 1;

		// 8. Make R4 low
		pPortDOutReg->pin_3 = 0;

		// Scan the columns
		// Check C1 (PD8) low or high
		if(!(pPortDInReg->pin_8 == 1)){
			delay();
			printf("*\n");
		}

		// Check C2 (PD9) low or high
		if(!(pPortDInReg->pin_9 == 1)){
			delay();
			printf("0\n");
		}

		// Check C3 (PD10) low or high
		if(!(pPortDInReg->pin_10 == 1)){
			delay();
			printf("#\n");
		}

		// Check C4 (PD11) low or high
		if(!(pPortDInReg->pin_11 == 1)){
			delay();
			printf("D\n");
		}
	}
}
